- improve UI
- dropdown of current assigned issues
- status result of adding comment
- change UI to show that you are not logged in
- add a reminder setting
- cmd+enter to submit
- hotkey
- Dropdown for
    -   jiras assigned to me
    -   jiras im watching
    -   jiras ive recently accessed